// <auto-generated/>
#nullable enable

namespace F0.Talks.SourceGenerators.Demo.Generated
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("F0.Talks.SourceGenerators.Demo", "1.0.0.0")]
    file static class Interceptors
    {
        private const string FilePath = @"Location\Program.cs";

        // [System.Runtime.CompilerServices.InterceptsLocation(FilePath, 20, 36)]
        internal static string Interceptor0(string text)
        {
            return $"Intercepted (static): {text}";
        }

        // [System.Runtime.CompilerServices.InterceptsLocation(FilePath, 21, 42)]
        internal static string Interceptor1(this F0.Talks.SourceGenerators.Demo.Interceptors.Intercepted instance, string text)
        {
            return $"Intercepted (instance): {text}";
        }
    }
}

namespace System.Runtime.CompilerServices
{
#pragma warning disable CS9113 // Parameter is unread.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("F0.Talks.SourceGenerators.Demo", "1.0.0.0")]
    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute(string filePath, int line, int character) : global::System.Attribute
    {
    }
#pragma warning restore CS9113 // Parameter is unread.
}
